#!/bin/bash
# Run this at the start of every session before any terraform apply
# that touches RDS or the Debezium EC2 security groups.
# Usage: bash scripts/update_my_ip.sh

set -e
MY_IP=$(curl -s https://checkip.amazonaws.com)
echo "Current public IP: ${MY_IP}"

cat > terraform/terraform.tfvars << TFVARS
# Auto-generated by scripts/update_my_ip.sh on $(date)
# IMPORTANT: This IP must be refreshed every session if it has changed.
allowed_cidr_blocks = ["${MY_IP}/32"]
TFVARS

echo "✅ terraform.tfvars updated with ${MY_IP}/32"
echo "Run 'terraform apply' to apply this IP to security groups."
